language: android
jdk: oraclejdk8
env:
  global:
    - GH_REF: github.com/snowwolf725/Unlock-LTE-Bands-App.git
    - secure: Qz2INaJeRFvIFI9LBlA2iMG85cPol1uaM8/5v3RnQfoFk2pgMRdINx3kPRq9KztVTCMWzjZBnrLmYfQHB2RhVK1G0WiRYZv/6KyQBFVpAtemlwP2bOmv4LmsP8QsOVnRblPS9VB6xQsziU8uK0lTFdZUXAcpp2IvfcI0S4d+4qhVsv+RtrsxSMdUHSpnJQa/BiKRRahmJdV7mZGe20+wEXTqXRX0WgY3IcQ7clywUD9M9gzb0mNTHnM0An5s4NpkHLoSak3GL1QN8/VUv7CLE+VoCNS0kGWjH5kAHLCzUkvXOtcwqjFpJxdOeQ9j68hfQdzjMFEyFQW1y5S5AQ4Rm0vQx35MGvmgDxcfEKmSoWBVhOHycsFYbeyK5xRj4Z/Q1GZI5inWRopdgp03SSmCNtnWVYDTdHBUV7+/gTKEkx4G2r0VTagGBDjOE4B8uORujonz/hkhKnXXsC10A+bNOBIjy2vPTkrSt6DwFzzEr1rr9Y54shjy5WM722y3/hJb2a7UF3kn77fKzHJXcIg0TORgG/Pspzcz+MtgjSxzf7bDUElwPokDHKEsSw76QDsaSPSmvKeIfobX9vIGE041K18CM1lDesrY5vTrPycf2crmkS2Emi6HXwT7J0d1MDqZH+lKpwk6esFe6hFtlS3dMid+lPJKtYEEvH2ebytnqiU=
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - chmod a+x gradlew
  - ./gradlew assembleRelease
deploy:
  provider: releases
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    tags: true
