language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - chmod a+x gradlew
  - ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: B4x7yGSqudgPvhq8yFFssMBXES6NHPk9JhHTMEHSjpVbbzuVDHONiD29i9q7D60PQrJIasUI21uqzX+UPSe5BjOT82kuaUIR3r9VDXZN5tCDiAMt/CyTs/Xo2F2GcY5cLstpOdn+tnfpNUAaqnleumLvSUUImIT9Ee3kqafXgzlzCXpEvjrqiuMg6qoI8Kn6/kLD0LveKpehzn0Bjk7PjhhvsLu8MtHhlL01UuO21sM+zqDa/5XN2UM6+vci3o3ebOCEBA46jx47caQ67WwKPXqYG3zveEmo1Hdad10JJygM38imsv8hh4CA14yk2h/i10bx95vtBW1LqBAjB/5kmLHdRfkPrlN+Kxo70ENqqnDdvSVxGWQgodL7lxUnT6IlV5DopbRCTYMxaS9J7boYdAbzYwR5MpYLjgwq9jYg2HIhgobldd74zyDGG6C/4MIvTKLEso+LzvIDZMBgCA+rCbzGDHu9dnQHM/yBwmurvXwOKXfFP+NrXNi+WqClyOKyyTiwmZ3h3lRsITXrhTUq9+HKMxoFzFCraU/N7PBHqfY0R55TnMWOSvuud5CmA3AuXB2V+7M5V0xSqBrc/Q2Zb91rijVZCXJsD/Ll+cP3ey0PznVJw+rZponmZmHWNBdtLYErfARpVjv1CSmsCSvu3Nk3Axi3dTvV/+vW/Up+cr8=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    tags: true
