language: android
jdk: oraclejdk8
env:
  global:
    - GH_REF: github.com/snowwolf725/Unlock-LTE-Bands-App.git
    - secure: "ztX8kF9ilfttfu24r2khs48r3Qvb2gv0JN8w5/CxqK84CCQI1JxdsGDiFusoUvtnFVdHflWl493a0fmNs6xouT/ykSm4eGomj5Cy1F1ndizw0fCyhwiPm6504DG+YubE+Q9JZunUR8uPKVRsWCJJOQFJ4gIyTzXU4Oe0rAZ1KLuMXZse8IJ91HOZk2r3jcj+Iq0/QXsCklPd9yifoKSZiTG7FDCt4/5EXDMQAVyveKzjq38ZOAj7B5rY37J6gHBz60r1XoNDBX/M5KQV5kJgl5rJBtVSd96TxdvGHnEl0+zgsPITSxRddiStbECr4lvAYD/z4tRejktt+i2FNMyMvrXzbTuwByBA5zHk2zo6jBjGYARN5pwLEPah+BoTTYp8lv6/qpRvAim75CLm9HpPxpdNqAPDLrpWv2SsDXzkD53t7yKD8cpxsYOmcMD7P3iPufIzABXWBpx3OVceGLH5/4wmgLb6RJzX7oUjo7Ox9dLcxrwB54Hl3/0MJqvxEZEcOlxCG+WycIfPSde76W7gjQ+yiPHbp0Uf8UTKKikOSvc6kqaodYk6ROULoSyHTH4B3XFvOpbyuFpUO5aIevy+2koamfmrrwERBDzQS8k+LTNHFRq9TsvE5sSB/7XJC4vhV0ai1N4DbRPbluEw1Uo1qmN0h1Ja/5AVGpU3YhqCR0E="
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - chmod a+x gradlew
  - ./gradlew assembleRelease
deploy:
  provider: releases
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
